#!/usr/bin/env python
import time
from watchdog.observers import Observer
import subprocess
import argparse
from fnmatch import fnmatch
import os.path as osp
import socket
import traceback

# local == your laptop or dev computer
# remote == cirrascale
LOCAL_DIR = "/Users/joschu/Proj/rllab"
REMOTE_DIR = "~/code/rllab"
LOCAL_HOSTNAME = "Johns-MacBook-Pro-3.local"
MACHINE_NAME = "ubuntu@52.41.64.90"

class Handler(object):
    def dispatch(self, event):
        src = event.src_path
        try:
            cmd = 'rsync -azvu -e "ssh -i /Users/joschu/OpenAI-Infra/joschu.pem" --delete  --exclude .git %s/ %s:%s/'%(LOCAL_DIR, MACHINE_NAME, REMOTE_DIR)
            print cmd
            subprocess.check_call(cmd, shell=True)
        except subprocess.CalledProcessError:
            traceback.print_exc()
if __name__ == "__main__":
    assert socket.gethostname() == LOCAL_HOSTNAME
    parser = argparse.ArgumentParser()
    observer = Observer()
    observer.schedule(Handler(), LOCAL_DIR, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(.25)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()

